# Generated by Django 5.0.3 on 2024-07-04 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('cod_area', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('email_area', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cli', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_cli', models.CharField(max_length=45)),
                ('apell_cli', models.CharField(max_length=45)),
                ('tel_cli', models.CharField(max_length=45)),
                ('dir_cli', models.CharField(max_length=45)),
                ('email_cli', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('email_con', models.CharField(max_length=45)),
                ('asunto', models.IntegerField(choices=[(0, 'Consulta'), (1, 'Reclamo'), (2, 'Sugerencia'), (3, 'Felicitación')])),
                ('mensaje', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('cod_maquina', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_maquina', models.CharField(max_length=45)),
                ('tipo_maquina', models.CharField(max_length=45)),
                ('cant_component', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='maquinas/')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('cod_ped', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_ped', models.DateField()),
                ('precio', models.FloatField()),
                ('cantidad', models.FloatField()),
                ('total', models.FloatField()),
                ('observaciones', models.CharField(max_length=45)),
                ('cod_maquina', models.ForeignKey(db_column='cod_maquina', on_delete=django.db.models.deletion.DO_NOTHING, to='BaseDeDatos.maquina')),
                ('id_cli', models.ForeignKey(db_column='id_cli', on_delete=django.db.models.deletion.CASCADE, to='BaseDeDatos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('cod_ord', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateField()),
                ('cant', models.FloatField()),
                ('remision_img', models.CharField(max_length=200)),
                ('cod_area', models.ForeignKey(db_column='cod_area', on_delete=django.db.models.deletion.DO_NOTHING, to='BaseDeDatos.area')),
                ('cod_maquina', models.ForeignKey(db_column='cod_maquina', on_delete=django.db.models.deletion.DO_NOTHING, to='BaseDeDatos.maquina')),
                ('cod_ped', models.ForeignKey(db_column='cod_ped', on_delete=django.db.models.deletion.CASCADE, to='BaseDeDatos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('cod_pieza', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_pieza', models.CharField(max_length=45)),
                ('tipo_material', models.CharField(max_length=45)),
                ('stock', models.IntegerField()),
                ('cod_maquina', models.ForeignKey(db_column='cod_maquina', on_delete=django.db.models.deletion.CASCADE, to='BaseDeDatos.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='users/usuario_defecto.jpg', upload_to='users/', verbose_name='Imagen de Perfil')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Direccion')),
                ('location', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ciudad')),
                ('telephone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefono')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'ordering': ['-id'],
            },
        ),
    ]
